# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for snet-tester2 (PySide6)

a = Analysis(
    ['snet_tester2/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('snet_tester2/resources/ui/main_window.ui', 'snet_tester2/resources/ui'),
        ('snet_tester2/resources/presets.json', 'snet_tester2/resources'),
    ],
    hiddenimports=[
        'snet_tester2',
        'snet_tester2.main',
        'snet_tester2.config',
        'snet_tester2.protocol',
        'snet_tester2.protocol.codec',
        'snet_tester2.protocol.constants',
        'snet_tester2.protocol.convert',
        'snet_tester2.protocol.enums',
        'snet_tester2.protocol.parser',
        'snet_tester2.protocol.types',
        'snet_tester2.transport',
        'snet_tester2.transport.base',
        'snet_tester2.transport.serial',
        'snet_tester2.transport.mock',
        'snet_tester2.comm',
        'snet_tester2.comm.events',
        'snet_tester2.comm.commands',
        'snet_tester2.comm.worker',
        'snet_tester2.state',
        'snet_tester2.state.statistics',
        'snet_tester2.views',
        'snet_tester2.views.helpers',
        'snet_tester2.views.main_window',
        'snet_tester2.views.plot_view',
        'snet_tester2.views.response_tracker',
        'snet_tester2.views.rx_panel',
        'snet_tester2.views.tx_panel',
        'PySide6.QtUiTools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt5', 'PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='snet-tester2',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
