"""SNET protocol constants."""

HEADER = b'\xA5\x5A'

# Frame byte indices
FRAME_IDX_STX_H = 0
FRAME_IDX_STX_L = 1
FRAME_IDX_SEQ = 2
FRAME_IDX_ID = 3
FRAME_IDX_CH = 4
FRAME_IDX_CMD_H = 5
FRAME_IDX_CMD_L = 6
FRAME_IDX_LEN = 7
FRAME_HEADER_LEN = 8
FRAME_IDX_PAYLOAD = FRAME_HEADER_LEN

# Frame defaults
FRAME_ID_DEFAULT = 0x00
FRAME_CH_DEFAULT = 0x00

# Command codes
READ_VAR_CMD = 0x0001
REQUEST_CMD = 0x8000
RESPONSE_CMD = 0x8100
WRITE_VAR_CMD = 0x0002
BROOKS_REQUEST_CMD_BASE = 0x1000
BROOKS_RESPONSE_DIR_BIT = 0x0100
BROOKS_GET_KP_CMD_L = 0x4C
BROOKS_GET_KP_DUMMY_LEN = 8
BROOKS_KP_SCALE = 10000.0
BROOKS_GET_KP_TIMEOUT_S = 1.0
BROOKS_KP_STATUS_LEN = 2
BROOKS_KP_DOUBLE_LEN = 8
BROOKS_KP_STATUS_OK = 0x0040

# Limits
MAX_PAYLOAD_LEN = 64
MAX_CHANNELS = 6
SEQ_START = 0xC0

# I/O defaults
IO_CONTROL_MODE_DEFAULT = 0x00
IO_OVERRIDE_DEFAULT = 0x00

# Conversion scales
RATIO_FULL_SCALE_RAW = 0x8000
TEMPERATURE_FULL_SCALE_RAW = 0x8000
TEMPERATURE_FULL_SCALE_C = 130.0
PRESSURE_FULL_SCALE_RAW = 0x8000
PRESSURE_FULL_SCALE_PSI = 130.0
FLOW_FULL_SCALE_RAW = 0x8000
FLOW_FULL_SCALE_PERCENT = 130.0

# Monitor
SNET_MONITOR_HEADER_LEN = 6

# Variable indices
WRITE_VAR_READ_AD_FLAG_INDEX = 0x0001
WRITE_VAR_MODE_FLAG_INDEX = 0x0002      # RUN=0, CAL=1
WRITE_VAR_FULL_OPEN_CONTROL_FLAG_INDEX = 0x0003
FULL_OPEN_VALUE_VAR_INDEX = 0x1000
FULL_OPEN_VALUE_SCALE = 1000
BROOKS_DEFAULT_SLAVE_ID = 0x01
BROOKS_KP_VALUE_COUNT = 6

# Display
FRAME_FIXED_FIELDS = ('STX', 'SEQ', 'ID', 'CH', 'CMD', 'LEN')
PLACEHOLDER = '--'
HEX_DUMP_BYTES_PER_LINE = 16

# Timing defaults
SAMPLE_PERIOD_S = 0.05
